# app/reporting/exporter.py
"""Export inspection results to timestamped Markdown / JSON reports + annotated image."""

import json
import os
from datetime import datetime


class ReportExporter:
    """Persist pipeline output: {image_stem}_{timestamp}.md / .json / annotated .jpg"""

    def __init__(self, out_dir: str = "reports"):
        self.out_dir = out_dir

    def export(self, image_path: str, det_result: dict, vlm_report: str,
               standards: list, draw_fn=None, decisions: list = None) -> dict:
        """Export a full report. draw_fn(image_path, det_result, out_path) draws bboxes."""
        decisions = decisions or []
        os.makedirs(self.out_dir, exist_ok=True)
        stem = os.path.splitext(os.path.basename(image_path))[0]
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        base = os.path.join(self.out_dir, f"{stem}_{ts}")
        paths = {"markdown": base + ".md", "json": base + ".json"}

        # 1. Markdown report
        md = self._to_markdown(image_path, det_result, vlm_report,
                               standards, decisions)
        with open(paths["markdown"], "w", encoding="utf-8") as f:
            f.write(md)

        # 2. JSON report (machine-readable, for future API layer)
        payload = {
            "generated_at": datetime.now().isoformat(timespec="seconds"),
            "image": image_path,
            "detection": {
                "inference_ms": det_result["inference_ms"],
                "counts": det_result["counts"],
                "detections": det_result["detections"],
            },
            "vlm_report": vlm_report,
            "agent_decisions": decisions,
            "standards": [
                {
                    "standard": s["standard"],
                    "source": s["source"],
                    "relevance": round(1 - s["distance"], 3),
                    "excerpt": s["text"][:300],
                }
                for s in standards
            ],
        }
        with open(paths["json"], "w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False, indent=2)

        # 3. Annotated image (bbox overlay)
        if draw_fn is not None:
            paths["annotated_image"] = base + "_det.jpg"
            try:
                draw_fn(image_path, det_result, paths["annotated_image"])
            except Exception as e:  # annotation failure should not kill the report
                print(f"  [warn] annotation skipped: {e}")
                paths.pop("annotated_image")

        return paths

    # ------------------------------------------------------------------ #
    def _to_markdown(self, image_path: str, det_result: dict,
                     vlm_report: str, standards: list,
                     decisions: list = None) -> str:
        decisions = decisions or []
        lines = []
        lines.append(f"# Visual Inspection Report")
        lines.append("")
        lines.append(f"| Field | Value |")
        lines.append(f"|-------|-------|")
        lines.append(f"| Image | `{image_path}` |")
        lines.append(f"| Generated | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} |")
        lines.append(f"| Objects detected | {sum(det_result['counts'].values())} |")
        lines.append(f"| Inference time | {det_result['inference_ms']} ms |")
        lines.append("")

        # Detection summary
        lines.append("## 1. Detection Summary")
        lines.append("")
        if det_result["counts"]:
            lines.append("| Class | Count |")
            lines.append("|-------|-------|")
            for cls, n in sorted(det_result["counts"].items(),
                                 key=lambda x: -x[1]):
                lines.append(f"| {cls} | {n} |")
        else:
            lines.append("*No objects detected above threshold.*")
        lines.append("")

        # VLM analysis (already contains 4-section structure)
        lines.append("## 2. VLM Analysis")
        lines.append("")
        lines.append(vlm_report)
        lines.append("")

        # Standards
        lines.append("## 3. Applicable Standards (RAG)")
        lines.append("")
        if standards:
            for i, s in enumerate(standards, 1):
                rel = 1 - s["distance"]
                lines.append(f"### [{i}] {s['standard']} "
                             f"(relevance: {rel:.2f})")
                lines.append("")
                lines.append(f"*Source: {s['source']}*")
                lines.append("")
                lines.append("> " + s["text"][:400].replace("\n", "\n> "))
                lines.append("")
        else:
            lines.append("*No relevant standards found.*")
            lines.append("")

        # Agent decisions
        if decisions:
            lines.append("## 4. Agent Decisions")
            lines.append("")
            for d in decisions:
                lines.append(f"- {d}")
            lines.append("")

        lines.append("---")
        lines.append("*Generated by visual-inspection-report-generator "
                     "(YOLOv8m + Qwen-VL-Max + RAG)*")
        lines.append("")
        return "\n".join(lines)
